### ISSUE TITLE
1.12.2使用时无法使用

### ISSUE THREAD

**Issue by 945374316** [R-Josef/ShootEXP#2]
我在1.12.2版本中使用，出现报错无法正常使用..
https://paste.ubuntu.com/p/dtwMMdqTBK/

**Comment by R-Josef** [comment]
你好，感谢你的反馈。  

```
[21:17:02 WARN]: [ShootEXP] Task #51 for ShootEXP v1.1 generated an exception
java.lang.NoSuchFieldError: BONE_MEAL
        at moe.feo.shootexp.EXP.genEXPItem(EXP.java:94) ~[?:?]
        at moe.feo.shootexp.EXP.<init>(EXP.java:43) ~[?:?]
        at moe.feo.shootexp.Couple$1.checkNum(Couple.java:76) ~[?:?]
        at moe.feo.shootexp.Couple$1.run(Couple.java:42) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
```
首先关于第一个报错，直接原因是spigot目前的版本更改了骨粉的名称，然后就出现了没有找到属性的错误。但是由于我在插件中使用了一个1.14才出现的，[持久化储存api](https://www.spigotmc.org/threads/a-guide-to-1-14-persistentdataholder-api.371200/)，1.14之前的版本，只能通过nms写nbt非常麻烦，我不是很熟悉，所以除非我解决了这个大问题，不然在其他地方做向下兼容没有任何意义。
```
[21:18:00 INFO]: Tirol issued server command: /shootexp
[21:18:00 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'shootexp' in plugin ShootEXP v1.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1401) [spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1236) [spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_281]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_281]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
        at moe.feo.shootexp.Commands.onCommand(Commands.java:87) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
        ... 15 more
```
关于第二个报错，这确实应该是个Bug，我会在之后修复。  

如果我之后有时间的话，会看看能不能做个低版本支持的。

**Comment by 945374316** [comment]
好的，如果可以的话，希望推出一个低版本支持

**Comment by R-Josef** [comment]
有个大佬已经做了1.12.2的支持了 #3 。
